package com.springdrools.rules

import com.springdrools.model.Item;

rule "Classify Item - Low Range"
    when
        $i: Item(cost < 200)
    then
        $i.setCategory(Item.Category.LOW_RANGE);
end

rule "Apples on Sale"
    when
        $i: Item(name == "Apples")
    then
        $i.setDiscount(0.2);
end

rule "Bananas on Sale"
    when
        $i: Item(name == "Bananas")
    then
        $i.setDiscount(0.1);
end